#! /bin/sh

# SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

# PICOM
# i think i broke it somewhere else :shrug:
systemctl --user import-environment XAUTHORITY DISPLAY
systemctl --user start picom.service

# MONITORS
autorandr -c

if [ $(autorandr -c | grep detected | cut -f 1 -d ' ') = dual ]
then
  bspc monitor eDP -d IV VI 
  bspc monitor DisplayPort-1-0 -d I II III V VII VIII IX X 
else
  bspc monitor eDP -d I II III IV V VI VII VIII IX X
fi


# SETTINGS
xsetroot -cursor_name left_ptr
bspc config border_width         2          
bspc config window_gap          12

bspc config active_border_color  "#585b70"
bspc config focused_border_color "#cce8aa"
bspc config normal_border_color  "#1e1e2e"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true


# APPLICATION RULES
bspc rule -a Zathura state=tiled

# BAR




# WALLPAPER
feh --bg-scale /home/nikhil/.config/bspwm/walls/mononoke.jpg --no-fehbg

# INITIAL BRIGHTNESS
brightness=$(cat "$HOME/.config/sparrow/.brightness")
light -s sysfs/backlight/amdgpu_bl2 -S $brightness
